### ISSUE TITLE
How can paginated models be transformed?

### ISSUE THREAD

**Issue by gabriel-vasile** [themsaid/laravel-model-transformer#3]
Hey, nice package, but the transformer works only with a model or collection. What about paginated results?

Thanks.

**Comment by themsaid** [comment]
You need to convert the pagination results to a collection first:

``` php
ItemTransformer::transform(collect($items->paginate(10)->items()));
```

**Comment by themsaid** [comment]
@VasileGabriel good?

**Comment by gabriel-vasile** [comment]
I solved it by getting the items from the paginator with getCollection(), transforming them and the building another paginator containing the end results. Thanks for help.

**Comment by marktimbol** [comment]
Hi Themsaid, very nice package!

I'm trying to transform the paginated posts but with no luck. I also tried this code that you suggested and I'm getting an error 
Type error: Argument 1 passed to App\Transformers\PostTransformer::transformModel() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Support\Collection given, called in /home/vagrant/code/demo/vendor/themsaid/laravel-model-transformers/src/AbstractTransformer.php on line 38

```php
ItemTransformer::transform(collect($items->paginate(10)->items()));
```

Thanks

**Comment by paulschwarz** [comment]
What about this?

```php
   $pagedResults; // Pagination instance

   ItemTransformer::transform($pagedResults->getCollection());

   $pagedResults; // ... is still is still the original pagination instance, but the collection has been manipulated
```

**Comment by ghost** [comment]
it's not working with `collect` with me `transformModel() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Support\Collection given`
