### ISSUE TITLE
Is supported with Laravel 5.3?

### ISSUE THREAD

**Issue by noprobz09** [themsaid/laravel-model-transformer#4]
Hi,

I found your package very simple but yet very useful, I tried to install it on Laravel 5.3 version but it seems it has an error. Is there any version that would support Laravel 5.3?

Thanks,
Noel

**Comment by themsaid** [comment]
Hello,

Can you share the error please?

**Comment by noprobz09** [comment]
I think its now fixed, Sorry for the false alarm, I just run the "composer self-update" first and after that I installed your package and everything is fine now :)

**Comment by themsaid** [comment]
nice :)
