### ISSUE TITLE
I got error on my model transformer

### ISSUE THREAD

**Issue by noprobz09** [themsaid/laravel-model-transformer#5]
Hello, 

I have problem in using the model transformer, on the controller I called it using this line
`$appointments = Appointment::where('field', condition)->get();
        return Response()->json(['appointments' => AppointmentTransformer::transform( $appointments )], 200);` and my model transformer is 
`

```
class AppointmentTransformer extends Themsaid\Transformers\AbstractTransformer{
public function transformModel(Model $item)
    {
        $output = [
           "field_key" => value
        ];

        return $output;
    }

}

```

and I get below error: 
**Declaration of AppointmentTransformer::transformModel() should be compatible with Themsaid\Transformers\AbstractTransformer::transformModel(Illuminate\Database\Eloquent\Model $modelOrCollection)**. Is there any way how can I fixt this? Thanks :)

**Comment by olgundutkan** [comment]
+1

**Comment by DelightedD0D** [comment]
Couldnt for the life me figure out why this happens. I ended up just changing the function name in my class like:

`public function transformModels`  

Now there can be no conflict ;)

**Comment by themsaid** [comment]
This is fixed now
