### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by theofidry** [themsaid/laravel-model-transformer#6]
I know the consumer API is not really the "Laravel way", but wouldn't it be better to work on a Laravel integration of the [Symfony Serializer](http://symfony.com/doc/current/components/serializer.html) rather than re-inventing the wheel? Actually the serializer offer you a couple more features:

- It figures out how to serializer/deserialize your objects automatically, so no need for custom serializers. So instead of having a custom Transformer, you would just need to register the serializer instead.
- If you need a more granular serialization, for example to display only a few properties or not allow the deserialization of some properties (user password), you can always use groups for it

I had a bit of trouble to use for my app to be honest, mainly because Eloquent models are a bit special making them hard to automatically serialize. I eventually got over it by using [EloquentSerializer](https://github.com/theofidry/EloquentSerializer) though.

WDYT?

**Comment by themsaid** [comment]
Sorry for not noticing your issue earlier, but I believe the package is fine as it is, simple enough and does the job :)
